name: React Native Voice Processor Example

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!example/README.md'
      - '!README.md'
      - '!test/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '**'
      - '!example/README.md'
      - '!README.md'
      - '!test/**'

jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        include:
        - node-version: 16.x
          gradle-version: 6.5
          agp-version: 4.1.3
          java-version: 11
          rn-version: 0.65.3
        - node-version: 18.x
          gradle-version: 7.5
          agp-version: 7.4.2
          java-version: 11
          rn-version: 0.71.12
        - node-version: 20.x
          gradle-version: 8.2
          agp-version: 8.2.2
          java-version: 17
          rn-version: 0.72.10

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Use Gradle ${{ matrix.gradle-version }}
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ matrix.gradle-version }}

    - name: Inject AGP version
      run: echo agpVersion="${{ matrix.agp-version }}" >> local.properties
      working-directory: example/android

    - name: Install dependencies
      run: yarn bootstrap

    - name: Change React Native versions
      run: yarn upgrade react-native@${{ matrix.rn-version }}
      working-directory: example

    - name: Copy project files
      if: ${{ (matrix.gradle-version == '8.2') || (matrix.gradle-version == '6.5')}}
      run: sh copy.sh
      working-directory: resources/.test/gradle_${{ matrix.gradle-version }}

    - name: Generate gradle wrapper
      run: gradle wrapper --gradle-version ${{ matrix.gradle-version }} --distribution-type all
      working-directory: example/android

    - name: Build bundle
      run: yarn example android-bundle

    - name: Build
      run: ./gradlew assembleDebug
      working-directory: example/android

  build-ios:
    runs-on: macos-12

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn bootstrap

    - name: Build bundle
      run: yarn example ios-bundle

    - name: Build
      run: xcrun xcodebuild build
        -configuration Debug
        -workspace VoiceProcessorExample.xcworkspace
        -sdk iphoneos
        -scheme VoiceProcessorExample
        -derivedDataPath ddp
        CODE_SIGNING_ALLOWED=NO
      working-directory: example/ios
